[package]
name 	= "engine_macro"
version = "0.1.0"
edition = "2024"

[dependencies]
syn 	= { version = "2.0"    }
quote   = { version = "1.0"    }
darling = { version = "0.23.0" }

[lib]
proc-macro = true